name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and Typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-env

      - name: Lint files
        run: pnpm lint

      - name: Typecheck files
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-env

      - name: Run unit tests
        run: pnpm test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-library:
    runs-on: ubuntu-latest
    name: Build Library
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-env

      - name: Build package
        run: pnpm build

      - name: Calculate Size
        if: github.ref != 'refs/heads/main'
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test-website:
    runs-on: ubuntu-latest
    name: Test Website
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-env
        with:
          working-directory: ./website

      - name: Build website
        working-directory: ./website
        run: pnpm build
